#!/bin/sh

# Produce individual UFOs from Glyphs files
psfglyphs2ufo --nofea source/AndikaMtihaniRoman.glyphs source -l source/logs/glyphs2ufoR.log
psfglyphs2ufo --nofea source/AndikaMtihaniItalic.glyphs source -l source/logs/glyphs2ufoI.log

./preflight