#!/bin/sh

# This normalization will also run check and fix routines
echo "-----Normalizing UFOs..."
psfnormalize -p checkfix=fix source/AndikaMtihani-Regular.ufo     &
psfnormalize -p checkfix=fix source/AndikaMtihani-Bold.ufo        &
psfnormalize -p checkfix=fix source/AndikaMtihani-Italic.ufo      &
psfnormalize -p checkfix=fix source/AndikaMtihani-BoldItalic.ufo  &
wait

# Building composites - needs to be done after normalization or may complain due to bad anchor coordinates
echo "-----Building composites..."
psfbuildcomp -q -i source/composites.txt source/AndikaMtihani-Regular.ufo     &
psfbuildcomp -q -i source/composites.txt source/AndikaMtihani-Bold.ufo        &
psfbuildcomp -q -i source/composites.txt source/AndikaMtihani-Italic.ufo      &
psfbuildcomp -q -i source/composites.txt source/AndikaMtihani-BoldItalic.ufo  &
wait

echo "-----Updating production names in Regular..."
psfsetpsnames -q -i source/glyph_data.csv source/AndikaMtihani-Regular.ufo -p backup=False -x

echo "-----Updating glyph orders in Regular..."
psfsetglyphorder -q --header sort_final -i source/glyph_data.csv source/AndikaMtihani-Regular.ufo -p backup=False -x

echo "-----Syncing glyph orders, psnames, and other metadata to other UFOs..."
psfsyncmasters -q source/AndikaMtihaniRoman.designspace source/AndikaMtihaniItalic.designspace

echo "-----Preflight completed!"
