#!/bin/sh

# This normalization will also run check and fix routines
psfnormalize -p checkfix=fix source/AndikaMtihani-Regular.ufo -l source/logs/normR.log
psfnormalize -p checkfix=fix source/AndikaMtihani-Bold.ufo  -l source/logs/normB.log
psfnormalize -p checkfix=fix source/AndikaMtihani-Italic.ufo -l source/logs/normI.log
psfnormalize -p checkfix=fix source/AndikaMtihani-BoldItalic.ufo -l source/logs/normBI.log

# Building composites - needs to be done after normalization or may complain due to bad anchor coordinates
psfbuildcomp -i source/composites.txt source/AndikaMtihani-Regular.ufo -l source/logs/compsR.log
psfbuildcomp -i source/composites.txt source/AndikaMtihani-Bold.ufo -l source/logs/compsB.log
psfbuildcomp -i source/composites.txt source/AndikaMtihani-Italic.ufo -l source/logs/compsI.log
psfbuildcomp -i source/composites.txt source/AndikaMtihani-BoldItalic.ufo -l source/logs/compsBI.log

psfsetpsnames -i source/glyph_data.csv source/AndikaMtihani-Regular.ufo -l source/logs/psnames.log -x
psfsetglyphorder --header sort_final -x -i source/glyph_data.csv source/AndikaMtihani-Regular.ufo -l source/logs/sortorder.log -x

# Following sync will copy psnames and glyphorder updates to all fonts
psfsyncmasters source/AndikaMtihaniRoman.designspace source/AndikaMtihaniItalic.designspace -l source/logs/sync.log
