#!/bin/sh

# Produce individual UFOs from Glyphs files
psfglyphs2ufo source/AndikaMtihani-RB.glyphs source
psfglyphs2ufo source/AndikaMtihani-IBI.glyphs source

# This normalization will also run check and fix routines
psfnormalize -p checkfix=fix source/AndikaMtihani-Regular.ufo
psfnormalize -p checkfix=fix source/AndikaMtihani-Bold.ufo
psfnormalize -p checkfix=fix source/AndikaMtihani-Italic.ufo
psfnormalize -p checkfix=fix source/AndikaMtihani-BoldItalic.ufo

psfsetpsnames -i source/glyph_data.csv source/AndikaMtihani-Regular.ufo
psfsetglyphorder --header sort_final -i source/glyph_data.csv source/AndikaMtihani-Regular.ufo

# Following sync will copy psnames and glyphorder updates to all fonts
psfsyncmasters source/AndikaMtihani-RB.designspace source/AndikaMtihani-IBI.designspace
